version: '3'
services:

  db_postgres:
    image: postgres:15
    hostname: my-postgres-container
    environment:
      POSTGRES_USER: lsi
      POSTGRES_PASSWORD: lsilsilsi
      POSTGRES_DB: lsi_kintaikanri
      POSTGRES_INITDB_ARGS: "--encoding=UTF8 --lc-collate=en_US.UTF-8 --lc-ctype=en_US.UTF-8"
    volumes:
      - ./db_postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./dbdata:/var/lib/postgresql/data
    restart: always
    mem_limit: 1g
    ports:
      - 5432:5432
    networks:
      - lsi_attendance_system

  pgadmin:
    depends_on:
      - db_postgres
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: lsi@email.com
      PGADMIN_DEFAULT_PASSWORD: lsilsilsi
    ports:
      - 8080:80
    networks:
      - lsi_attendance_system

  app:
    depends_on:
      - db_postgres
    build: 
      context: ./php
      dockerfile: Dockerfile
    volumes:
      - ./app:/var/www/html
      - ./php/php.ini:/usr/local/etc/php/conf.d/php.ini
    networks:
      - lsi_attendance_system

  www:
    depends_on:
      - app
    image: nginx:latest
    restart: always
    volumes:
      - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
      - ./app:/var/www/html
    ports:
      - 80:80
    networks:
      - lsi_attendance_system

volumes:
  dbdata:

networks:
  lsi_attendance_system:
    driver: bridge
