version: '3'
services:
  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: lsi_db
      MYSQL_USER: lsi
      MYSQL_PASSWORD: lsilsilsi
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    ports:
        - 4306:3306
    volumes:
      - "./db:/docker-entrypoint-initdb.d"
    networks:
      - lsi_attendance_system

  app:
    depends_on:
      - db
    build: 
      context: ./php
      dockerfile: Dockerfile
    volumes:
      - ./app:/var/www/html
      - ./php/php.ini:/usr/local/etc/php/conf.d/php.ini
    networks:
      - lsi_attendance_system

  www:
    depends_on:
      - app
    image: nginx:latest
    restart: always
    volumes:
      - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
      - ./app:/var/www/html
    ports:
      - 80:80
    networks:
      - lsi_attendance_system

  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: lsilsilsi
    restart: always
    ports:
      - 8080:80
    networks:
      - lsi_attendance_system

networks:
  lsi_attendance_system:
    driver: bridge
